### ISSUE TITLE
very high memory consumption

### ISSUE THREAD

**Issue by openpaul** [ZhangZhenmiao/METAMVGL#2]
Hello,
I thought a new ticket might be best:

I noticed that the python script requires a lot of memory. In my case my input file sizes are:
```
245 Mb prepared.ag
20 Mb prepared.pe
3.6 Gb alignment.bam
```
And the job will require more than 700 GB of memory. 

Is that correct or am I doing something wrong?

**Comment by openpaul** [comment]
Seems like this was a bug in an early version. Now it seems like it runs fine. 

I modified your script a bit in order to debug it. Maybe it helps you too:
https://github.com/openpaul/METAMVGL/blob/black/METAMVGL.py

**Comment by openpaul** [comment]
I am sorry I spoke too soon. So I did some testing and get easily over 100GB in memory, at which the job was killed, bc that seemed too much.

The log file looks like this using the linked modified version above
```
2020-10-21T14:54:40+00:00:  binned contigs after remove ambiguous: 3757                           
2020-10-21T14:54:40+00:00:  Identifying non isolated contigs                                      
2020-10-21T15:12:33+00:00:  non isolated contigs: 115264                                          
2020-10-21T15:12:33+00:00:  non isolated binned contigs: 878                                      
2020-10-21T15:12:34+00:00:  Preparing graph  
```

The memory consumption spikes at these lines it seems:

```
assembly_graph_degree = np.diag(degree)
assembly_graph_adjacent = nx.adjacency_matrix(assembly_graph, nodelist=non_isolated).A
```

Is that to be expected?

I plotted memory consumption over time here:
![memory](https://user-images.githubusercontent.com/3997610/96733107-fde8db00-13b0-11eb-909e-0575dbfba6bc.png)

**Comment by ZhangZhenmiao** [comment]
Hi,

Thanks for the analysis. Based on the debug info and memory consumption over time, I guess np.dot might be very memory consuming for large or sparse matrices ...

**Comment by openpaul** [comment]
This isn't a particular large dataset (as far as our datasets go), do you have a test dataset which you could provide?
How much memory does a normal run consume (roughly)?

**Comment by ZhangZhenmiao** [comment]
Here is an [example](https://drive.google.com/drive/folders/1o2aE2yoqlh_6EQZ8Wf6U6drBCcqGPsq5?usp=sharing) in the test dataset (SYHTH64, SRX200676, total sequence 5.8Gbp). The file sizes are:
```
197M    contigs.fasta (by metaSPAdes)
403M    assembly_graph.fastg (by metaSPAdes)
5.6G    align.spades.bam (by BWA)
3.7M    graph_output.ag (by prep_graph)
2.8M    graph_output.pe (by prep_graph)
```
prep_graph finished in 536s with a maximum memory of 40.3g:
```
Start loading fastg ...
Loaded 61843 edges, 131900 links.
Done.
Start loading spades paths ...
Loaded 28245 paths.
Done.
Start parsing alignments ...
Parsed 10000000 lines ...
Parsed 20000000 lines ...
Parsed 30000000 lines ...
Parsed 40000000 lines ...
Parsed 50000000 lines ...
Parsed 60000000 lines ...
Parsed 70000000 lines ...
Parsed 80000000 lines ...
Parsed 90000000 lines ...
Parsed 100000000 lines ...
Parsed 105886428 lines ...
Done.
Start constructing links between paths ...
Constructed links of 10000 paths, new links 23045 ...
Constructed links of 20000 paths, new links 23064 ...
Constructed links of 28245 paths, new links 14047 ...
Done.
Start constructing PE overlap ...
Constructed PE overlap of 1000 paths, new overlaps 5378 ...
Constructed PE overlap of 2000 paths, new overlaps 7831 ...
......
Constructed PE overlap of 164000 paths, new overlaps 7762 ...
Constructed PE overlap of 164928 paths, new overlaps 5838 ...
Done.
Start traversing assembly graph ...
Traversed edge neighbours of 10000 paths ...
Traversed edge neighbours of 20000 paths ...
Traversed edge neighbours of 28245 paths ...
Done.
Start traversing PE graph ...
Traversed PE neighbours of 10000 paths ...
Traversed PE neighbours of 20000 paths ...
Traversed PE neighbours of 28245 paths ...
Done.
```
METAMVGL.py finished in 375s with a maximum memory of 42.2g:
```
initial binned contigs: 12808
binned contigs after remove ambiguous: 7750
non isolated contigs: 19184
non isolated binned contigs: 3904
Iteration 0  Alpla0 0.013625829235742603  Alpla1 0.014058597032683605  Obj_value 72.2604409371944
Iteration 1  Alpla0 0.013623018079651505  Alpla1 0.01406182983520357  Obj_value 72.25983661734928
Iteration 2  Alpla0 0.013622978287730531  Alpla1 0.014061874372743954  Obj_value 72.25983120457877
Iteration 3  Alpla0 0.013622977732303112  Alpla1 0.014061874994176575  Obj_value 72.25983112963084
final binned contigs: 23030
final binned contigs after remove ambiguous: 21169
```

You can reproduce the result by running ```bash test.sh```, and ```test.log``` is the standard output for reference.

**Comment by openpaul** [comment]
Thank you, will try it and see if I get the same results. 

Your example has 19k non isolate contigs while my test dataset had >100k, if that translates into matrix dimension the memory footprint might grow quite fast and could explain the difference?

Maybe there could be an option to trim by length? Many of the contigs in the graph are likely very small. Honestly I did not read the code enough to suggest anything, but might be worth optimizing this as metagenomic datasets seem to grow in size every year.

I might run it again on a different community and see how it does then, will have to run some assemblies first (I think I dont have graphs for most of my assemblies anymore). 

Thanks again for being so helpful.

**Comment by ZhangZhenmiao** [comment]
Hi,

I totally rewrite the matrices multiplication (np.dot) to the form of sparse matrices in METAMVGL.py. Now in the test [example](https://drive.google.com/drive/folders/1o2aE2yoqlh_6EQZ8Wf6U6drBCcqGPsq5), the python script only takes 5.7Gb memory in 159s. You can download the updated [METAMVGL.py](https://github.com/ZhangZhenmiao/METAMVGL/blob/main/METAMVGL.py) to see if that works in your dataset.

**Comment by ZhangZhenmiao** [comment]
close because of inactivity
