### ISSUE TITLE
程序中断

### ISSUE THREAD

**Issue by mant-ux** [ZhangZhenmiao/METAMVGL#4]
您好 ，我成功运行了metamvgl.py获得了结果，但是用的是一个7000条contig的数据集，当我想再跑一个21000条的大一些的数据集的时候，prep_graph无法成功获得pe图和装配图，程序显示如下，这可能是内存原因吗？
<img width="153" alt="image" src="https://user-images.githubusercontent.com/82646017/115009648-1577cb00-9edf-11eb-81f7-a02651c9096b.png">

**Comment by ZhangZhenmiao** [comment]
您好，“已杀死”看起来像是因为内存不够了，也许可以尝试用内存更大的机器运行。如果可以分享给我数据，我可以运行下看看是不是内存原因，谢谢～

**Comment by mant-ux** [comment]
感谢回复！确实是内存问题，我将虚拟机的内存调高了便成功运行了，谢谢哥

**Comment by mant-ux** [comment]
还有一个问题想请教一下哥，您这篇高作是对graphbin的改进提升，但我观察graphbin源代码数据集，比如基于megahit的ESC，14617条contig，只给了2000多个真实标签，并且把他的基于megahit的gfa图文件构成接邻矩阵后构成的边保存下来，发现14617个结点也只有大约不到2000条边，这种边结构不丰富的装配图，真的可以获得那样良好的聚类效果？其他数据集的边也不是很丰富，而且我用ncbi数据库上的真实sharon数据集基于spades拼接构图得到的边，与blastn的标签比对结果进行对照，发现边的连接与类别之间关系并不是很明显啊，这里我存在很大疑问，谢谢您的回复！十分崇拜您，祝哥事业更上一层楼。

**Comment by ZhangZhenmiao** [comment]
你好，在我们实验中也发现megahit的组装图的边比较少，对聚类效果的提升有限。对于sharon数据集的spades组装图，它的边与类别之间的关系不明显可能有几方面原因，可能是1. 物种间重复序列造成的；2. 高复杂度降低了组装图的精确度；3. 测序错误造成了组装图的错误的边，这些原因导致了组装图有时候不能有效提升聚类效果，所以我们在聚类中引入了双端测序信息。感谢你关注我们的研究，祝好～
